### ISSUE TITLE
Fireworks/task_db credentials

### ISSUE THREAD

**Issue by montoyjh** [materialsproject/mongogrant#3]
Today I was helping someone using mongogrant to try to set up a fireworks/atomate pipeline, and we got some feedback that it was a bit convoluted (basically we connected via the normal instructions and then looked at the written config for credentials).  I was thinking we might consider developing a rudimentary CLI that connected to a given database and created something like a tasks_db.json or my_launchpad.yaml automatically.  Atomate might be a better place for this, though, so it might just be that we add a bit of mongogrant integration into atomate.

**Comment by dwinston** [comment]
I also got some feedback that the process of token renewal should be easily handled via a CLI. I think this is a good suggestion.

**Comment by dwinston** [comment]
@shyamd @montoyjh there is a rudimentary CLI (`mgrant`) now. `pip install -U mongogrant` to have a look.
